server:
  port: 8080

spring:
  application:
    name: blockchain-learning
  web:
    resources:
      add-mappings: true

blockchain:
  infura:
    project-id: "${INFURA_PROJECT_ID:YOUR_ID}"
  network:
    name: "sepolia"
    chain-id: 11155111
    display-name: "Sepolia Testnet"
  
  wallet:
    storage-path: "${WALLET_STORAGE_PATH:./wallets}"
    encryption-key: "${WALLET_ENCRYPTION_KEY:a-16-byte-secret}"
  
  contract:
    gas-limit: 4700000
    gas-price: 20000000000

logging:
  level:
    org.web3j: INFO
    com.blockchain.learning: DEBUG
    root: INFO

explorer:
  api:
    url: "https://api-sepolia.etherscan.io/api"
    key: "${ETHERSCAN_API_KEY:XX2615RJXVUKZIVKSAMGQDADWCM2N6FNQB}"